const photos=[
['photo-01','Discobar Galaxie Night Shift','Club','wide'],['photo-02','Milow','Portrait','tall'],['photo-03','Discobar Galaxie','Club',''],['photo-04','Discobar Galaxie','Club','wide'],['photo-05','Sylvie Kreusch','Concert','tall'],['photo-06','Sylvie Kreusch','Concert',''],['photo-07','Sylvie Kreusch','Concert','tall'],['photo-08','Editors','Concert','wide'],['photo-09','Discobar Galaxie','Club',''],['photo-10','Selah Sue','Concert',''],['photo-11','Discobar Galaxie','Club','tall'],['photo-12','Selah Sue','Concert',''],['photo-13','Editors','Concert','wide'],['photo-14','Dressed Like Boys','Concert','tall'],['photo-15','Selah Sue','Concert',''],['photo-16','Liam Gallagher','Concert','wide'],['photo-17','Balthazar','Concert',''],['photo-18','Discobar Galaxie','Club','tall'],['photo-19','Noémie Wolfs','Portrait',''],['photo-20','Equal Idiots','Concert','wide'],['photo-21','Editors','Concert',''],['photo-22','Roosbeef','Concert','tall'],['photo-23','Discobar Galaxie','Club',''],['photo-24','Roosbeef','Concert','wide'],['photo-25','Dressed Like Boys','Concert',''],['photo-26','Pixies','Concert','wide'],['photo-27','Discobar Galaxie','Club',''],['photo-28','Discobaar A Moeder','Club','wide'],['photo-29','Discobaar A Moeder','Club',''],['photo-30','Discobar Galaxie Night Shift','Club','tall'],['photo-31','Oldskool XXL','Club','wide']];
const gallery=document.querySelector('#gallery');
if(gallery){const render=(filter='all')=>{gallery.innerHTML=photos.map((p,i)=>{let [id,title,cat,cls]=p;return cat.toLowerCase()===filter||filter==='all'?`<article class="card ${cls}" data-index="${i}" data-category="${cat.toLowerCase()}"><img loading="lazy" src="assets/images/${id}-900.jpg" srcset="assets/images/${id}-480.jpg 480w, assets/images/${id}-900.jpg 900w, assets/images/${id}-1600.jpg 1600w" sizes="(max-width: 700px) 50vw, ${cls==='wide'?'66vw':'33vw'}" alt="${title} — live fotografie"><div class="card-meta"><span>${title}</span><span>${cat}</span></div></article>`:''}).join('');gallery.querySelectorAll('.card').forEach(c=>c.addEventListener('click',()=>openBox(+c.dataset.index)))};render();document.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(b=>b.classList.remove('active'));btn.classList.add('active');render(btn.dataset.filter);setTimeout(()=>document.querySelectorAll('.card').forEach(c=>c.classList.add('is-visible')),20)}));}
const box=document.querySelector('.lightbox');let current=0;function openBox(i){if(!box)return;current=i;const p=photos[i], img=box.querySelector('img');img.src=`assets/images/${p[0]}-1600.jpg`;img.alt=p[1];box.querySelector('figcaption').textContent=`${p[1]} — ${p[2]}`;box.classList.add('open');box.setAttribute('aria-hidden','false')}function closeBox(){box?.classList.remove('open');box?.setAttribute('aria-hidden','true')}function step(n){current=(current+n+photos.length)%photos.length;openBox(current)}box?.querySelector('.close').addEventListener('click',closeBox);box?.querySelector('.prev').addEventListener('click',()=>step(-1));box?.querySelector('.next').addEventListener('click',()=>step(1));box?.addEventListener('click',e=>{if(e.target===box)closeBox()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeBox();if(e.key==='ArrowLeft')step(-1);if(e.key==='ArrowRight')step(1)});
document.querySelector('.menu-toggle')?.addEventListener('click',()=>document.querySelector('.site-header').classList.toggle('nav-open'));
document.querySelector('#contact-form')?.addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,status=document.querySelector('.form-status'),data=Object.fromEntries(new FormData(f));status.textContent='Bericht wordt verzonden…';try{const r=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const out=await r.json();if(!r.ok)throw Error(out.message);status.textContent=out.message;f.reset()}catch(err){const subject=encodeURIComponent('Fotografie aanvraag van '+data.name);const body=encodeURIComponent(`Naam: ${data.name}\nEmail: ${data.email}\n\n${data.message}`);window.location.href=`mailto:info@jorenvanutterbeeck.be?subject=${subject}&body=${body}`;status.textContent='Backend niet beschikbaar — je mailprogramma wordt geopend…'}});
// Reveal cards as they enter the viewport, like the editorial image flow on ViV.
const reveal=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');reveal.unobserve(entry.target)}}),{threshold:.08});document.querySelectorAll('.card').forEach((card,i)=>{card.style.transitionDelay=`${(i%4)*70}ms`;reveal.observe(card)});
const cursor=document.querySelector('.cursor-label');document.querySelectorAll('.card').forEach(card=>{card.addEventListener('mouseenter',()=>cursor?.classList.remove('hidden'));card.addEventListener('mouseleave',()=>cursor?.classList.add('hidden'));card.addEventListener('mousemove',e=>{if(cursor){cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px'}})});
// Curated visual themes — remembered between visits.
const themePanel=document.querySelector('#theme-panel');
const themeTrigger=document.querySelector('.theme-trigger');
const savedTheme=localStorage.getItem('joren-theme')||'noir';
document.body.dataset.theme=savedTheme;
function closeThemes(){themePanel?.classList.remove('open');themeTrigger?.setAttribute('aria-expanded','false')}
themeTrigger?.addEventListener('click',e=>{e.stopPropagation();const open=themePanel.classList.toggle('open');themeTrigger.setAttribute('aria-expanded',open)});
themePanel?.querySelectorAll('[data-theme-choice]').forEach(btn=>btn.addEventListener('click',()=>{const theme=btn.dataset.themeChoice;document.body.dataset.theme=theme;localStorage.setItem('joren-theme',theme);closeThemes()}));
document.addEventListener('click',e=>{if(themePanel&&!themePanel.contains(e.target)&&e.target!==themeTrigger)closeThemes()});
